name: "build"
on: "push"

env:
  CGO_ENABLED: "0"
  GOOS: "linux"

jobs:
  build:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        arch: ["386", "amd64", "arm", "arm64"]
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-go@v2"
        with:
          go-version: ">=1.17.7"
      - run: "go build -v -a -o gesundheit-${GITHUB_REF##*/}-${{ matrix.arch }} ."
        env:
          GOARCH: "${{ matrix.arch }}"
      - if: startsWith(github.ref, 'refs/tags/')
        uses: "softprops/action-gh-release@v1"
        with:
          files: "gesundheit-*"

  pkgbuild:
    runs-on: "ubuntu-latest"
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: "actions/checkout@v2"
      - run: |
          sed -i "s/pkgver=.\+/pkgver=${GITHUB_REF##*/}/g" PKGBUILD
          docker run -i -v $(pwd):/build archlinux/archlinux:base-devel <<EOF
            pacman -Syu --noconfirm
            pacman -S --noconfirm go
            groupadd -g 1000 build
            useradd -m -u 1000 -g 1000 build
            mkdir -m 0777 /build/pkg
            chown build:build /build/pkg
            cd /build/pkg
            cp ../PKGBUILD .
            su build -s /usr/bin/bash -c "makepkg --skipchecksums"
          EOF
      - uses: "softprops/action-gh-release@v1"
        with:
          files: "pkg/gesundheit-*.pkg.*"
