name: "build"
on: "push"

env:
  CGO_ENABLED: "0"
  GOOS: "linux"

jobs:
  build:
    name: "build"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        arch: ["amd64", "arm", "arm64"]
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-go@v2"
        with:
          go-version: ">=1.17.7"
      - run: "go build -v -a -o gesundheit-${{ matrix.arch }} ."
        env:
          GOARCH: "${{ matrix.arch }}"
      - if: startsWith(github.ref, 'refs/tags/')
        uses: "softprops/action-gh-release@v1"
        with:
          files: "gesundheit-${{ matrix.arch }}"
